name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd my-app
          npm install

      - name: Run Tests
        run: |
          cd my-app
          npm test -- --watchAll=falsese

      - name: Build Project
        run: |
          cd my-app
          npm run build
